---
title: "Graph course final project"
author: Shumin Liu
format:
  dashboard:
    orientation: rows
execute: 
  echo: false
#theme: superhero
---

```{python}
import pandas as pd
import plotly.express as px
import numpy as np
import itables
import country_converter as cc
import panel as pn
```

```{python}
# Load the Human Development Index data
hdi = pd.read_csv("data/hdi_human_development_index.csv")

# Convert the dataframe from wide to long
hdi_long = hdi.melt(
  id_vars = ["geo", "name"],
  var_name = "year",
  value_name = "human_development_index").rename(columns = {"name": "country"})

# Filter data from 2000 onwards
hdi_long["year"] = hdi_long["year"].astype(int)

#hdi_long = hdi_long.query("year >= 2000")

# Create a subset for 2023
hdi_2023 = hdi_long[hdi_long["year"] == 2023]
hdi_2023["geo"] = hdi_2023["geo"].str.upper()

hdi_top_10_countries = hdi_2023.nlargest(10, "human_development_index").sort_values(
    by = "human_development_index",
    ascending = False
)

hdi_top_10_data = hdi_long[hdi_long["country"].isin(hdi_top_10_countries["country"])]
```

```{python}
# Load the GPD per capita data
gdp_pcap = pd.read_csv("data/gdp_pcap.csv")

# Convert the dataframe from wide to long
gdp_pcap_long = gdp_pcap.melt(
  id_vars = ["geo", "name"],
  var_name = "year",
  value_name = "gdp_per_capita").rename(columns = {"name": "country"})

# Filter data from 2000 onwards
gdp_pcap_long["year"] = gdp_pcap_long["year"].astype(int)

#gdp_pcap_long = gdp_pcap_long.query("year >= 2000")

# Categorise the gpd per capita based on actual historical data and future projection
# The threshold is determined based on https://www.gapminder.org/data/documentation/gd001/
def categorise_year (y):
  if y <= 2022:
    return "Actual"
  else:
    return "Future Projection"

categorise_year_vec = np.vectorize(categorise_year)

gdp_pcap_long["year_category"] = categorise_year_vec(gdp_pcap_long["year"])
```

```{python}
# Load life expectancy data
life_exp = pd.read_csv("data/lex.csv")

# Convert the dataframe from wide to long
life_exp_long = life_exp.melt(
  id_vars = ["geo", "name"],
  var_name = "year",
  value_name = "life_expectancy").rename(columns = {"name": "country"})

# Filter data from 2000 onwards
life_exp_long["year"] = life_exp_long["year"].astype(int)

life_exp_long = life_exp_long.query("year >= 2000")
```

```{python}
# Data visualization for the first indicator

# A map for HDI in 2023
hdi_map = px.choropleth(
    hdi_2023,
    locations = "geo",
    color = "human_development_index",
    hover_name = "country",
    title = "Map of Countries by Human Development Index in 2023",
    color_continuous_scale = "Blues",
).update_layout(coloraxis_showscale = False)

# Trends of HDI for ten countries that had the highest HDI in 2023

# Create the line chart
hdi_10_line_chart = px.line(hdi_top_10_data,
  x = "year",
  y = "human_development_index",
  color = "country",
  markers = True,
  labels = {"year": "Year", 
            "human_development_index": "Human Development Index"},
  title = "Changes in Human Development Index over time among the top ten countries in 2023")

hdi_10_line_chart = hdi_10_line_chart.update_layout(
    legend_title_text = "",
    legend = dict(
        entrywidth = 150,           # adjust as needed
        entrywidthmode = "pixels",
        orientation = "h",
        yanchor = "bottom",
        y = -0.35,
        xanchor = "center",
        x = 0.5
    )
)

```

```{python}
# Data visualization for the second indicator

# Create calculate the average GDP per capita over time
gdp_pcap_avg = gdp_pcap_long.groupby(["year", "year_category"]).agg(mean_gdp_pcap = ("gdp_per_capita", "mean")).reset_index()

# Create a bar chart
gdp_pcap_avg_bar = px.bar(gdp_pcap_avg,
                          x = "year",
                          y = "mean_gdp_pcap",
                          color = "year_category",
                          labels = {"year": "Year", "mean_gdp_pcap": "Average GDP per Capita"},
                          title = "Global Average GDP per Capita over time")

gdp_pcap_avg_bar = gdp_pcap_avg_bar.update_layout(
    legend_title_text = "",
    legend=dict(
        entrywidth=100,           # adjust as needed
        entrywidthmode="pixels",
        orientation="h",
        yanchor="bottom",
        y=-0.35,
        xanchor="center",
        x=0.5)
)

# Create a bar chart for countries that have high std based on actual historical data
gdp_pcap_std = (
  gdp_pcap_long.query("year >= 1990 and year <= 2022")
  .groupby("country")
  .agg(mean_gdp_pcap = ("gdp_per_capita", "mean"), 
       std_gdp_pcap = ("gdp_per_capita", "std"))
  .nlargest(10, "std_gdp_pcap")
  .sort_values(by = "std_gdp_pcap", ascending = False)
  .reset_index()
)

gdp_pcap_std_bar = px.bar(gdp_pcap_std,
                      x = "country",
                      y = "mean_gdp_pcap",
                      error_y = "std_gdp_pcap",
                      labels = {"country": "Country", "mean_gdp_pcap": "Average GDP per Capita"},
                      title = "Average GDP per capita of the top ten countries with strongest fluctuation<br>based on available data from 1990 to 2022")

gdp_pcap_std_bar = gdp_pcap_std_bar.update_layout(
  title = dict(
        text = "Average GDP per capita of the top ten countries with strongest fluctuation<br>based on available data from 1990 to 2022",
        x = 0.5,  # Center the title
        xanchor = 'center',
        font = dict(size = 16)),
  margin = dict(t = 60)
)

# Create a line chart for these ten countries
gdp_std_top_10_data = gdp_pcap_long[gdp_pcap_long["country"].isin(gdp_pcap_std["country"])].query("year >= 1990 and year <= 2022")

gdp_std_top_10_line = px.line(gdp_std_top_10_data,
  x = "year",
  y = "gdp_per_capita",
  color = "country",
  labels = {"year": "Year", 
            "gdp_per_capita": "GDP per Capita"},
  title = "GDP per capita of the top ten countries with strongest fluctuation<br>based on available data from 1990 to 2022")

gdp_std_top_10_line = gdp_std_top_10_line.update_layout(
  legend_title_text = "",
    legend=dict(
        entrywidth=120,           # adjust as needed
        entrywidthmode="pixels",
        orientation="h",
        yanchor="bottom",
        y=-0.35,
        xanchor="center",
        x=0.5),
    title = dict(
        text = "GDP per capita of the top ten countries with strongest fluctuation<br>based on available data from 1990 to 2022",
        x = 0.5,  # Center the title
        xanchor = 'center',
        font = dict(size = 16)),
  margin = dict(t = 60)
)
```


```{python}
# Data visualization for relationship bewteen two indicators

# Prepare data :merge hdi and gdp per capital data
hdi_gdp_combined = pd.merge(hdi_long, gdp_pcap_long, on = ["country", "geo", "year"], how = "inner")

hdi_gdp_scatter = px.scatter(hdi_gdp_combined,
  x = "gdp_per_capita",
  y = "human_development_index",
  hover_name = "country",
  animation_frame = "year",
  labels = {"human_development_index": "Human Development Index", 
            "gdp_per_capita": "GDP per Capita",
            "year": "Year"},
  title = "GDP per capita of the top ten countries with biggest changes based on available data from 1990 to 2022",
  template = "simple_white"
  )
```


# Human Development Index

## Row 1.1 - Map & Text box {height=50%}

### Column 1.1.1 {width="60%"}
```{python}
hdi_map
```

### Column 1.1.2 {width="40%"}
::: {.card}
#### Insights
<style>
.card {
  font-size: 20px;
}
</style>

In the map of countries by Human Development Index (HDI) in 2023, countries located in North America, Oceania, and Europe have higher HDI in general. 


The top ten countries with high HDI are Iceland, Switzerland, Norway, Denmark, Germany, Sweden, Australia, Netherlands, Belgium, and Ireland. By tracing their HDI trajectory from 1990, it shows that Ireland made the most significant progress by growing from 0.776 in 1990 to 0.949 in 2023. In general, the HDI presented an upward trend, though the slope of growth became more flat, showing the HDI got more stable.
:::

## Row 1.2 {height=50%}

### Column 1.2.1 {width="60%"}
```{python}
hdi_10_line_chart
```

### Column 1.2.2 {width="40%"}
```{python}
itables.show(
    hdi_top_10_countries.reset_index(drop=True),
    caption = "Top 10 Countries by HDI in 2023",
    searching = False
)
```

# GDP per Capita

## Row 2.1 {height=45%}

### Column 2.1.1 {width="50%"}
```{python}
gdp_pcap_avg_bar
```

### Column 2.1.2 {width="50%"}
::: {.card}
#### Insights
<style>
.card {
  font-size: 18px;
}
</style>

According to [the documentation of GDP per Capita](https://www.gapminder.org/data/documentation/gd001/), data between 1990 and 2022, our series are identical to [the GDP per capita data from the World Bank](https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD), published in April 2024 in their World Development Indicators. Data prior to 1990 are from other sources. It is observed that data from 2022 onwards are available. Therefore, it is assumed that data prior to 2022 are the actual historical data while data beyond 2022 are the future projection.

The bar chart on the left hand side is the global average GDP per Capita over time, showing exponential growth. The slope becomes steeper after 1950s. In the recent ten years, the average GDP per Capital has been growing, except a mild recession in 2020.The future project shows a positive upward trend in continuous growth.

By reviewing data from 1990 to 2022 and calculating , the top five countries that show strongest fluctuation in terms of standard deviation are Monaco, Qatar, Singapore, Ireland, and Luxembourg. Among them, Monaco experienced the biggest change, GDP per Capita growing from 166,038 in 1990 to 440,710 in 2022.
:::

## Row 2.2 {height=55%}

### Column 2.2.1 {width="50%"}
```{python}
gdp_std_top_10_line
```

### Column 2.2.2 {width="50%"}
```{python}
gdp_pcap_std_bar
```

# Page 3
